stages:
  - test_build
  - test
  - build
  - showroom_deploy
  - stage_deploy
  - prod_deploy

variables:
  REPOSITORY: "$REGISTRY_SERVER/$CI_PROJECT_PATH/$CI_COMMIT_REF_SLUG"

before_script:
  - echo "$REPOSITORY:$CI_COMMIT_SHA"


test_build:
  stage: test_build
  tags:
    - deploy
  only:
    variables:
      - $IN_STAGE_TYPE == "test"
  script:
    - echo "test build"

test:
  stage: test
  tags:
    - deploy
  only:
    variables:
      - $IN_STAGE_TYPE == "test"
  script:
    - echo "test"



Build:
  stage: build
  script:
    - dapp dimg build --verbose --name $CI_PROJECT_PATH_SLUG
    - dapp dimg push --verbose --name $CI_PROJECT_PATH_SLUG $REPOSITORY --tag=$CI_COMMIT_SHA --registry-username $REGISTRY_LOGIN --registry-password $REGISTRY_PASSWORD
  tags:
    - deploy
  except:
    variables:
      - $IN_STAGE_TYPE == "test"


Deploy to showroom:
  stage: showroom_deploy
  when: manual
  environment:
    name: showroom
  script:
    - dapp --version
    - dapp kube deploy
      --verbose
      --name $CI_PROJECT_PATH_SLUG
      --namespace $NAMESPACE
      --set "namespace=$NAMESPACE"
      --set "image.repository=$REPOSITORY"
      --set "image.tag=$CI_COMMIT_SHA"
      $REPOSITORY
  variables:
    NAMESPACE: developers
  tags:
    - deploy
  except:
    variables:
      - $IN_STAGE_TYPE == "test"
      - $CI_BUILD_REF_NAME == "master"
      - $CI_BUILD_REF_NAME == "production"

Deploy to staging:
  stage: stage_deploy
  environment:
    name: staging
  script:
    - dapp --version
    - dapp kube deploy
      --verbose
      --name $CI_PROJECT_PATH_SLUG
      --namespace $NAMESPACE
      --set "namespace=$NAMESPACE"
      --set "image.repository=$REPOSITORY"
      --set "image.tag=$CI_COMMIT_SHA"
      $REPOSITORY
  variables:
    NAMESPACE: staging
  tags:
    - staging
  only:
    - master


deploy to prod:
  stage: prod_deploy
  when: manual
  environment:
    name: production
  script:
    - dapp --version
    - dapp kube deploy
      --verbose
      --name $CI_PROJECT_PATH_SLUG
      --namespace $NAMESPACE
      --set "namespace=$NAMESPACE"
      --set "image.repository=$REPOSITORY"
      --set "image.tag=$CI_COMMIT_SHA"
      $REPOSITORY
  variables:
    NAMESPACE: production
  tags:
    - prod
  only:
    - production
