stages:
  - test_build
  - test
  - build
  - deploy

variables:
  REPOSITORY: "$REGISTRY_SERVER/$CI_PROJECT_PATH/$CI_COMMIT_REF_SLUG"
  DIST_IMAGE: "$REGISTRY_SERVER/$CI_PROJECT_PATH/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA"
  HELM_RELEASE_NAME: "$CI_PROJECT_PATH_SLUG-$NAMESPACE"

before_script:
  - echo "$DIST_IMAGE"
  - echo "$HELM_RELEASE_NAME"


Test build:
  stage: test_build
  tags:
    - test
  only:
    variables:
      - $IN_STAGE_TYPE == "test"
  script:
    - echo "test build"

Test:
  stage: test
  tags:
    - test
  only:
    variables:
      - $IN_STAGE_TYPE == "test"
  script:
    - echo "test"



Build:
  stage: build
  script:
    - dapp version
    - dapp bp
      --name $CI_PROJECT_PATH_SLUG
      --repo $REGISTRY_SERVER
      --registry-username $REGISTRY_LOGIN
      --registry-password $REGISTRY_PASSWORD
      --tag $CI_COMMIT_SHA
  tags:
    - build
  except:
    variables:
      - $IN_STAGE_TYPE == "test"


Deploy to showroom:
  stage: deploy
  when: manual
  environment:
    name: showroom
  script:
    - dapp version
    - dapp deploy $HELM_RELEASE_NAME
      --name $CI_PROJECT_PATH_SLUG
      --namespace $NAMESPACE
      --tag=$CI_COMMIT_SHA
      --set "namespace=$NAMESPACE"
      --set "image.nodejs=$DIST_IMAGE"
      --set "image.pullSecretName=$REGISTRY_PULL_SECRET_NAME"
      --repo $REGISTRY_SERVER
  variables:
    NAMESPACE: developers
  tags:
    - showroom
  except:
    variables:
      - $IN_STAGE_TYPE == "test"

Deploy to staging:
  stage: deploy
  environment:
    name: staging
  script:
    - dapp version
    - dapp deploy $HELM_RELEASE_NAME
      --name $CI_PROJECT_PATH_SLUG
      --namespace $NAMESPACE
      --tag=$CI_COMMIT_SHA
      --set "namespace=$NAMESPACE"
      --set "image.nodejs=$DIST_IMAGE"
      --set "image.pullSecretName=$REGISTRY_PULL_SECRET_NAME"
      --repo $REGISTRY_SERVER
  variables:
    NAMESPACE: staging
  tags:
    - staging
  only:
    - master


Deploy to prod:
  stage: deploy
  when: manual
  environment:
    name: production
  script:
    - dapp version
    - dapp deploy $HELM_RELEASE_NAME
      --name $CI_PROJECT_PATH_SLUG
      --namespace $NAMESPACE
      --tag=$CI_COMMIT_SHA
      --set "namespace=$NAMESPACE"
      --set "image.nodejs=$DIST_IMAGE"
      --set "image.pullSecretName=$REGISTRY_PULL_SECRET_NAME"
      --repo $REGISTRY_SERVER
  variables:
    NAMESPACE: production
  tags:
    - prod
  only:
    - production
