export const enum FilterConditionEnum {
  Is = 'is',
  IsNot = 'isNot',
  IsIn = 'isIn',
  IsNotIn = 'isNotIn',
  StartsWith = 'startsWith',
  EndsWith = 'endsWith',
  Contains = 'contains',
  DoesNotContain = 'doesNotContain',
  IsDate = 'isDate',
  IsNotDate = 'isNotDate',
  AfterDate = 'afterDate',
  BeforeDate = 'beforeDate',
  BetweenDates = 'betweenDates',
  GreaterThan = 'greaterThan',
  LessThan = 'lessThan',
  Between = 'between',
}
