export enum PaymentActionsEnum {
  Cancel = 'cancel',
  ShippingGoods = 'shipping_goods',
  Refund = 'refund',
  Return = 'return',
  Authorize = 'authorize',
  Capture = 'capture',
  ChangeAmount = 'change_amount',
  Collection = 'collection',
  LatePayment = 'late_payment',
  Paid = 'paid',
  Remind = 'remind',
  Upload = 'upload',
  Edit = 'edit',
  Verify = 'verify',
}
