export enum PaymentActionsEnum {
  Cancel = 'cancel',
  ShippingGoods = 'shipping_goods',
  Refund = 'refund',
  Return = 'return',
  Authorize = 'authorize',
  ChangeAmount = 'change_amount',
  Collection= 'collection',
  LatePayment = 'late_payment',
  Paid = 'paid',
  Remind = 'remind',
  Upload = 'upload',
  Edit = 'edit',
  DownloadShippingLabel = 'download_shipping_label',
  DownloadShippingSlip = 'download_shipping_slip',
}
