apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}

  labels:
    app: {{ .Chart.Name }}

  annotations:
    {{ .Chart.Name }}/deploy-timestamp: {{ now }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Chart.Name }}

  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}

    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ '/usr/local/bin/npm', 'run', 'start' ]

          ports:
            - containerPort: {{ .Values.service.containerPort }}
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /api/status
              port: {{ .Values.service.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /api/status
              port: {{ .Values.service.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 5

          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}

            - configMapRef:
                name: nodejs-micro-url-map

            - secretRef:
                name: {{ .Chart.Name }}

          env:
            - name: KUBERNETES_DEPLOYED
              value: "{{ now }}"
