{{ $chartName := .Chart.Name }}
{{ $values := .Values }}
{{ $appName := $chartName }}

apiVersion: apps/v1
{{- if eq $values.namespace "production" }}
kind: DaemonSet
{{- else }}
kind: Deployment
{{- end }}
metadata:
  name: {{ $appName }}
  namespace: {{ $values.namespace }}

  labels:
    app: {{ $appName }}
    tier: nodejs
    type: http

  annotations:
    "werf.io/set-replicas-only-on-creation": "true"

spec:
  {{- if ne $values.namespace "production" }}
  replicas: {{ $values.replicas.http }}
  {{- end }}
  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: {{ $appName }}

  template:
    metadata:
      labels:
        app: {{ $appName }}
        tier: nodejs
        type: http

      annotations:
        seccomp.security.alpha.kubernetes.io/pod: 'runtime/default'

    spec:
      priorityClassName: {{ $values.priorityClass }}

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node_worker
                operator: Exists

      imagePullSecrets:
        - name: {{ $values.image.pullSecretName }}

      containers:
        - name: node
          image: {{ $values.image.nodejs }}
          imagePullPolicy: IfNotPresent
          command: [ "/bin/bash", "-c", "/payever/deploy/deploy.sh" ]

          lifecycle:
            preStop:
              exec:
                command: ["sleep", "15"]

          ports:
            - containerPort: {{ $values.service.containerPort }}
              protocol: TCP
              name: http

            - containerPort: 8080
              protocol: TCP
              name: tcp

          livenessProbe:
            httpGet:
              path: /api/status
              port: {{ $values.service.statusPort }}
            initialDelaySeconds: 150
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /api/status
              port: {{ $values.service.statusPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 15

          resources:
{{ toYaml $values.resources | indent 12 }}

          envFrom:
            - configMapRef:
                name: {{ $chartName }}
            - configMapRef:
                name: micro-url-map
            - secretRef:
                name: {{ $chartName }}

          env:
            - name: KUBERNETES_DEPLOYED
              value: "{{ now }}"
