{{ $chartName := .Chart.Name }}
{{ $values := .Values }}
{{ $appName := $chartName }}
{{ $consName := printf "%s-consumer" $chartName }}
{{ $wsName := printf "%s-ws" $chartName }}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ $appName }}
  name: {{ $appName }}
  namespace: {{ $values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {{ $appName }}
  minReplicas: {{ $values.replicas.http.min }}
  maxReplicas: {{ $values.replicas.http.max }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ $values.hpa.cpu.tarUti }}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ $values.hpa.mem.tarUti }}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ $consName }}
  name: {{ $consName }}
  namespace: {{ $values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {{ $consName }}
  minReplicas: {{ $values.replicas.consumer.min }}
  maxReplicas: {{ $values.replicas.consumer.max }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ $values.hpa.cpu.tarUti }}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ $values.hpa.mem.tarUti }}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ $wsName }}
  name: {{ $wsName }}
  namespace: {{ $values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {{ $wsName }}
  minReplicas: {{ $values.replicas.ws.min }}
  maxReplicas: {{ $values.replicas.ws.max }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ $values.hpa.cpu.tarUti }}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ $values.hpa.mem.tarUti }}
