namespace: default
priorityClass: app-9stars

image:
  nodejs: registry.devpayever.com/nodejs-backend/transactions
  rmq_repub: payeverk8sregistry.azurecr.io/infra/rmq_fallback_repub:1.1.0
  pullSecretName: regsecret

service:
  externalPort: 80
  containerPort: 3000
  statusPort: 8081
  wsPort: 8080

resources:
  requests:
    cpu: 156m
    memory: 284Mi
  limits:
    memory: 600Mi
#high
replicas:
  http:
    min: 5
    max: 20
  consumer:
    min: 5
    max: 20
  ws:
    min: 5
    max: 10
  cron: 1

hpa:
  cpu:
    tarUti: 75
  mem:
    tarUti: 85
