namespace: default
priorityClass: app-9stars

replicas:
  http: 1
  consumer: 1
  cron: 1

image:
  nodejs: registry.devpayever.com/nodejs-backend/transactions
  pullSecretName: regsecret

service:
  externalPort: 80
  containerPort: 3000
  statusPort: 8081

resources:
  requests:
    cpu: 32m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 1Gi
