namespace: default
priorityClass: app-9stars

replicas:
  http: 2
  consumer: 2
  cron: 2
  ws: 2

image:
  nodejs: registry.devpayever.com/nodejs-backend/transactions
  pullSecretName: regsecret

service:
  externalPort: 80
  containerPort: 3000
  statusPort: 8081
  wsPort: 8080

resources:
  requests:
    cpu: 32m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 1Gi
