namespace: default

replicaCount: 1

image:
  nodejs: registry.devpayever.com/nodejs-backend/transactions/master
  pullSecretName: regsecret

service:
  externalPort: 80
  containerPort: 3000

resources:
  requests:
    cpu: 32m
    memory: 256m
