namespace: default
priorityClass: app-9stars
enableRmqFallbackRepub: false
image:
  nodejs: registry.devpayever.com/nodejs-backend/transactions
  pullSecretName: regsecret

service:
  externalPort: 80
  containerPort: 3000
  statusPort: 8081
  wsPort: 8080

resourcestest:
  app:
    requests:
      cpu: 200m
      memory: 50Mi
    limits:
      memory: 350Mi
  consumer:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      memory: 150Mi
  consumer_export:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      memory: 350Mi
resourcesstage:
  app:
    requests:
      cpu: 200m
      memory: 50Mi
    limits:
      memory: 350Mi
  consumer:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      memory: 150Mi
  consumer_export:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      memory: 350Mi
resourceslive:
  app:
    requests:
      cpu: 156m
      memory: 284Mi
    limits:
      memory: 600Mi
  consumer:
    requests:
      cpu: 156m
      memory: 284Mi
    limits:
      memory: 600Mi
  consumer_export:
    requests:
      cpu: 256m
      memory: 284Mi
    limits:
      memory: 8Gi
#high
replicas:
  http:
    min: 5
    max: 20
  consumer:
    min: 5
    max: 20
  ws:
    min: 5
    max: 10
  cron: 1

hpa:
  cpu:
    tarUti: 75
  mem:
    tarUti: 85
