namespace: default

replicaCount: 1

image:
  nodejs: payeverk8sregistry.azurecr.io/nodejs-backend/transactions/master
  pullSecretName: regsecret

service:
  externalPort: 80
  containerPort: 3000
  statusPort: 8081

resources:
  requests:
    cpu: 32m
    memory: 128m
