namespace: default

replicaCount: 1

image:
  repository: registry.devpayever.com/nodejs-backend/transactions/master
  tag: latest
  pullPolicy: Always
  pullSecretName: regsecret

service:
  externalPort: 80
  containerPort: 3000
