namespace: default
priorityClass: app-9stars
image:
  nodejs: registry.devpayever.com/nodejs-backend/transactions
  pullSecretName: regsecret

service:
  externalPort: 80
  containerPort: 3000
  statusPort: 8081
  wsPort: 8080

resources:
  requests:
    cpu: 96m
    memory: 284Mi
  limits:
    cpu: 200m
    memory: 600Mi
#high
replicas:
  http:
    min: 5
    max: 20
  consumer:
    min: 5
    max: 20
  ws:
    min: 5
    max: 10
  cron: 1

hpa:
  cpu:
    tarUti: 75
  mem:
    tarUti: 85
